length_in_x: 20.0
length_in_y: 20.0
position_x: 0.0
position_y: 0.0
resolution: 0.1
min_variance: 0.00009
max_variance: 10000.0


mahalanobis_distance_threshold: 2.5 #2.5
multi_height_noise: 0.00002



